import { Content, GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";
import {
    classifyExpenseDeclaration,
    logToLedgerDeclaration,
    flagForReviewDeclaration,
    executeClassifyExpense,
    executeLogToLedger,
    executeFlagForReview,
} from "./tools";

dotenv.config();

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey || apiKey === "your_gemini_api_key_here") {
    console.log("No GEMINI_API_KEY found in .env file.");
    console.log("Please add your key to backend/.env: GEMINI_API_KEY=your_key");
    process.exit(1);
}

const genAI = new GoogleGenerativeAI(apiKey);

async function runDayOneDemo() {
    console.log("Initializing Gemini Agent with Function Calling Tools...\n");

    const model = genAI.getGenerativeModel({
        model: "gemini-3.6-flash",
        tools: [
            {
                functionDeclarations: [
                    classifyExpenseDeclaration,
                    logToLedgerDeclaration,
                    flagForReviewDeclaration,
                ],
            },
        ],
    });

    const userPrompt = `
You are an autonomous accounting agent for Ethiopian businesses.
Process the following transaction:
- Receipt ID: REC-2026-883
- Vendor: TotalEnergies Bole Service Station, Addis Ababa
- TIN: 0012938475
- Date: 2026-08-24
- Items: 75 Liters Diesel Fuel at 60 ETB/L
- Total Amount: 4500 ETB
- VAT Amount: 586.95 ETB

Instructions:
1. Determine the appropriate expense category, VAT, and withholding status.
2. Call the classifyExpense tool.
`;

    console.log("Sending prompt to Gemini...");
    console.log("Waiting for Gemini decision...\n");

    const contents: Content[] = [
        {
            role: "user",
            parts: [{ text: userPrompt }],
        },
    ];

    const initialResult = await model.generateContent({ contents });
    const response = initialResult.response;
    const functionCalls = response.functionCalls();

    if (!functionCalls || functionCalls.length === 0) {
        console.log("Gemini responded with text instead of calling a tool:");
        console.log(response.text());
        return;
    }

    const call = functionCalls[0];
    const args = (call.args || {}) as Record<string, any>;

    console.log("Gemini decided to call tool:", call.name);
    console.log("Arguments generated by Gemini:", JSON.stringify(args, null, 2), "\n");

    let toolResult: Record<string, any> = {};

    if (call.name === "classifyExpense") {
        toolResult = executeClassifyExpense(args);
        console.log("Executed local classifyExpense function:");
        console.log(toolResult, "\n");
    } else if (call.name === "logToLedger") {
        toolResult = executeLogToLedger(args);
        console.log("Executed local logToLedger function:");
        console.log(toolResult, "\n");
    } else if (call.name === "flagForReview") {
        toolResult = executeFlagForReview(args);
        console.log("Executed local flagForReview function:");
        console.log(toolResult, "\n");
    }

    const modelTurn = response.candidates?.[0]?.content;
    if (modelTurn) {
        contents.push(modelTurn);
    }

    contents.push({
        role: "user",
        parts: [
            {
                functionResponse: {
                    name: call.name,
                    response: {
                        output: toolResult,
                    },
                },
            },
        ],
    });

    console.log("Sending tool execution results back to Gemini...\n");

    const followUpResult = await model.generateContent({ contents });
    console.log("Gemini Final Agent Assessment:");
    console.log(followUpResult.response.text());
}

runDayOneDemo().catch((error) => {
    console.error("Agent execution error:", error);
});
